### ISSUE TITLE
Math.pow not working

### ISSUE THREAD

**Issue by mzaini30** [brettz9/french-press#1]
In CoffeeScript, if I write 1 *\* 3, the result is Math.pow(1,3)
Why not working in this add ons?
Thanks :D

**Comment by brettz9** [comment]
That was apparently a more recent innovation within CoffeeScript since the version I had included. I've uploaded a new version of my add-on, 0.3.2, with version 1.9.3 of CoffeeScript which allows such syntax. Hopefully, AMO will approve the update shortly. Thanks for the report!

p.s. I've also added the CoffeeScript library as a Bower dependency, so my lazy self can even more easily update it next time. :)

Closing for now, but feel free to comment further.
